openapi: 3.1.0
info:
  title: GPT-4.1 Call
  version: 1.0.0
paths:
  /v1/chat/completions:
    post:
      operationId: callOpenAIGPT41
      summary: Send a prompt to OpenAI's GPT-4.1 and return the response.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - model
                - messages
              properties:
                model:
                  type: string
                  example: gpt-4.1
                messages:
                  type: array
                  items:
                    type: object
                    required:
                      - role
                      - content
                    properties:
                      role:
                        type: string
                        example: user
                      content:
                        type: string
                        example: What is the capital of France?
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  choices:
                    type: array
                    items:
                      type: object
                      properties:
                        message:
                          type: object
                          properties:
                            content:
                              type: string
servers:
  - url: https://api.openai.com